import { useCallback, useEffect, useState } from "react";
type Entry = { name: string; directory: boolean }; type Approval = { id: string; type: string; summary: string };
type GitState = { branch: string; status: string; diff: string; worktrees: { path: string; head: string; branch: string }[] };
export type WorkspaceView = "files" | "git" | "terminal";
export function WorkspacePanel({ view }: { view: WorkspaceView }) {
  const api = window.cagent?.workspace; const [cwd, setCwd] = useState(""); const [path, setPath] = useState("."); const [entries, setEntries] = useState<Entry[]>([]); const [preview, setPreview] = useState("");
  const [git, setGit] = useState<GitState | null>(null); const [command, setCommand] = useState(""); const [terminalOutput, setTerminalOutput] = useState(""); const [terminalRunning, setTerminalRunning] = useState(false); const [approval, setApproval] = useState<Approval | null>(null); const [error, setError] = useState("");
  const [commitMessage, setCommitMessage] = useState(""); const [branchName, setBranchName] = useState(""); const [worktreeName, setWorktreeName] = useState(""); const [worktreeTarget, setWorktreeTarget] = useState(""); const [startRef, setStartRef] = useState("HEAD");
  const request = async (type: string, payload?: unknown) => { try { setError(""); const result = await api?.request(type, payload); if (result?.id) setApproval(result); return result; } catch (err) { setError(err instanceof Error ? err.message : String(err)); return null; } };
  const loadFiles = useCallback(async (next = ".") => { const result = await request("list", { path: next }); if (result) { setPath(result.path); setEntries(result.entries); } }, []);
  useEffect(() => { api?.request("root").then((result) => { setCwd(result.cwd); loadFiles(); }).catch((err) => setError(String(err))); return api?.onEvent((message) => { if (message.type === "workspace:approval") setApproval(message.payload); if (message.type === "terminal:data") setTerminalOutput((value) => value + message.payload.data); if (message.type === "terminal:status") setTerminalRunning(message.payload.running); if (message.type === "cwd:updated") { setCwd(message.payload.cwd); loadFiles(); } }); }, [api, loadFiles]);
  useEffect(() => { if (view === "git") request("git-status").then((value) => value && setGit(value)); }, [view]);
  const open = async (entry: Entry) => { const next = path === "." ? entry.name : `${path}/${entry.name}`; if (entry.directory) return loadFiles(next); const result = await request("read", { path: next }); setPreview(result?.content || ""); };
  const parent = path.split(/[\\/]/).slice(0, -1).join("/") || ".";
  return <section className="workspace-panel" aria-label="工作区检查器"><div className="inspector-path" title={cwd}>{cwd || "未选择项目"}</div>{error && <div className="workspace-error" role="alert">{error}</div>}
    {view === "files" && <><div className="inspector-actions"><button type="button" onClick={() => request("choose-directory")}>选择项目</button><button type="button" onClick={() => loadFiles()}>刷新</button></div><div className="workspace-tree">{path !== "." && <button type="button" onClick={() => loadFiles(parent)}>..</button>}{entries.length === 0 && !error && <div className="workspace-empty">暂无文件</div>}{entries.map((entry) => <button type="button" key={entry.name} onClick={() => open(entry)}><span>{entry.directory ? "目录" : "文件"}</span>{entry.name}</button>)}</div>{preview && <pre className="workspace-preview">{preview}</pre>}</>}
    {view === "git" && <><div className="inspector-actions"><button type="button" onClick={async () => setGit(await request("git-status"))}>刷新</button>{git && <button type="button" onClick={() => request("git-stage", { paths: git.status.split("\n").filter(Boolean).map((line) => line.slice(3).trim()) })}>暂存改动</button>}</div>{git ? <><pre className="workspace-output">{git.branch}{"\n"}{git.status || "工作区干净"}{"\n"}{git.diff}</pre><div className="inspector-form"><input value={commitMessage} onChange={(event) => setCommitMessage(event.target.value)} placeholder="提交说明" /><button type="button" disabled={!commitMessage.trim()} onClick={() => request("git-commit", { message: commitMessage })}>提交</button><input value={branchName} onChange={(event) => setBranchName(event.target.value)} placeholder="分支名称" /><button type="button" disabled={!branchName.trim()} onClick={() => request("git-branch", { name: branchName })}>创建分支</button><input value={worktreeName} onChange={(event) => setWorktreeName(event.target.value)} placeholder="Worktree 名称" /><input value={worktreeTarget} onChange={(event) => setWorktreeTarget(event.target.value)} placeholder="目标目录" /><input value={startRef} onChange={(event) => setStartRef(event.target.value)} placeholder="起始引用" /><button type="button" onClick={async () => { const result = await request("choose-worktree-target"); if (result?.target) setWorktreeTarget(result.target); }}>选择目录</button><button type="button" disabled={!worktreeName || !worktreeTarget} onClick={() => request("worktree-add", { name: worktreeName, target: worktreeTarget, startRef })}>添加 Worktree</button></div><div className="worktree-list">{git.worktrees.map((item) => <div key={item.path}><strong>{item.branch}</strong><span>{item.path}</span></div>)}</div></> : <div className="workspace-empty">正在加载 Git 状态...</div>}</>}
    {view === "terminal" && <><div className="terminal-status"><span className={terminalRunning ? "status-ready" : "status-idle"} />{terminalRunning ? "终端运行中" : "终端空闲"}</div><div className="inspector-actions"><button type="button" onClick={async () => { const result = await request("terminal-start"); if (result?.running) setTerminalRunning(true); }}>启动</button><button type="button" onClick={async () => { const result = await request("terminal-kill"); if (result && !result.running) setTerminalRunning(false); }}>终止</button></div><div className="terminal-command"><input value={command} onChange={(event) => setCommand(event.target.value)} placeholder="输入命令..." onKeyDown={(event) => { if (event.key === "Enter" && command.trim()) { request("terminal", { command }); setCommand(""); } }} /><button type="button" onClick={() => { if (command.trim()) { request("terminal", { command }); setCommand(""); } }}>运行</button></div><pre className="terminal-output">{terminalOutput || "终端已就绪"}</pre></>}
    {approval && <div className="modal-scrim"><section className="confirm-modal" role="dialog" aria-modal="true"><h2>需要授权</h2><p>{approval.summary}</p><div><button type="button" onClick={async () => { await request("deny", { id: approval.id }); setApproval(null); }}>拒绝</button><button type="button" onClick={async () => { await request("approve", { id: approval.id }); setApproval(null); }}>允许</button></div></section></div>}
  </section>;
}
